name: Discourse Plugin

on:
  push:
    branches:
      - main
      - master
  pull_request:
  schedule: 
    - cron: 22 05 * * *

jobs:
  ci:
    uses: discourse/.github/.github/workflows/discourse-plugin.yml@v1
